[build]
    command = "sh ./deploy.sh"
    functions = "functions/"
    publish = "public/"
[dev]
    command = "gatsby develop"
[[plugins]]
  package = "netlify-plugin-gatsby-cache"
[[redirects]]
    from = "/api/*"
    to = "/.netlify.functions/:splat"
    status = 200
[[redirects]]
    from = "/dashboard/*"
    to = "/dashboard"
    status = 200
[functions]
      included_files = ["libs/**"]
