name: Trigger Netlify Build
on: [push, pull_request]
  # schedule:
    # Run daily at 0100
    # - cron: "0 1 * * *"
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Curl request
        run: curl -X POST -d 'full' https://api.netlify.com/build_hooks/5fa2b3cb5a2f610d8ba0d0f6
