name: Trigger Netlify Build
on:
  schedule:
    # Run at every two hours
    - cron: "0 */2 * * *"
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
      - run: curl -X POST -d 'full' https://api.netlify.com/build_hooks/5fa2b3cb5a2f610d8ba0d0f6
